# Stage 1: Compile the distribution natively inside Docker
FROM eclipse-temurin:21-jdk-alpine AS builder
WORKDIR /build

# Copy your source code workspace files
COPY . .

# Sanitize Windows formatting line endings and grant execute permissions
RUN apk add --no-cache dos2unix && \
    dos2unix gradlew && \
    chmod +x gradlew

# Build the complete standalone native distribution folder structure
RUN ./gradlew installDist -x test

# Stage 2: Clean, ultra-lean production runtime image
FROM eclipse-temurin:21-jre-alpine
WORKDIR /app

# FIXED: Uses a wildcard to copy the generated folder, regardless of your project's name
COPY --from=builder /build/build/install/* ./

# Run the startup script natively generated by the Gradle application plugin
ENTRYPOINT ["./bin/app"]
