# Stage 1: Compile the distribution natively inside Docker
FROM eclipse-temurin:21-jdk-alpine AS builder
WORKDIR /build

# Copy your source code workspace files
COPY . .

# Sanitize Windows formatting line endings and grant execute permissions
RUN apk add --no-cache dos2unix && \
    dos2unix gradlew && \
    chmod +x gradlew

# Build the complete standalone native distribution folder structure
RUN ./gradlew installDist -x test

# Stage 2: Clean, ultra-lean production runtime image
FROM eclipse-temurin:21-jre-alpine
WORKDIR /app

# Copy the entire unpacked distribution folder built from Stage 1
# Gradle places this matching your project namespace (defaults to 'app')
COPY --from=builder /build/build/install/app ./

# Run the startup script natively generated by the Gradle application plugin
ENTRYPOINT ["./bin/app"]
